apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: "frnbmiby"
  POSTGRES_USER: "frnbmiby"
  POSTGRES_PASSWORD: "4B-ez4DaGrS4tKA6JcVuJjwopp-cDlYx"
