apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgress
spec:
  replicas: 1
  selector:
      matchLabels:
        app.kubernetes.io/name: sawtooth-0
  template:
    metadata:
      labels:
        app: postgress
    spec:
      containers:
        - name: postgress
          image: postgres:9.6.5
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
      
