apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: alpine
spec:
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  selector:
      matchLabels:
        app.kubernetes.io/name: sawtooth-0
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - image: alpine:latest
        name: alpine
        
