apiVersion: v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
      matchLabels:
        app.kubernetes.io/name: sawtooth-0
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: docker pull xcoulon/go-url-shortener:0.2.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
      
